# Generated by Django 4.1.2 on 2023-05-30 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0002_remove_person_birthday'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AddField(
            model_name='product',
            name='modelo',
            field=models.CharField(default=None, max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(max_length=2000),
        ),
    ]
