# Generated by Django 4.1.2 on 2023-05-30 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0004_alter_product_modelo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
