# Generated by Django 4.1.2 on 2023-06-04 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0005_remove_product_category_delete_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='amount',
        ),
    ]
