# Generated by Django 4.1.2 on 2023-06-04 00:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0006_remove_cart_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_api.person'),
        ),
    ]
